---
- name: Configure system and deploy Orthanc
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker
    - role: orthanc
      tags: orthanc