---
- name: Create Orthanc data directory
  file:
    path: /opt/orthanc
    state: directory
    owner: carebot
    group: carebot
    mode: 0755
  # Edge case: složka může být již vytvořena s jiným vlastníkem

- name: Pull Orthanc Docker image
  docker_image:
    name: jodogne/orthanc
    tag: latest
    source: pull
  # Edge case: přístup k Docker Hubu může být omezený

- name: Configure Orthanc
  template:
    src: orthanc.json.j2
    dest: "{{ orthanc_storage_dir }}/orthanc.json"
    owner: carebot
    group: carebot
    mode: 0644
  # Edge case: špatný formát JSON v šabloně by mohl způsobit selhání kontejneru

- name: Ensure Orthanc container is running
  docker_container:
    name: orthanc
    image: jodogne/orthanc
    state: started
    restart: yes
    ports:
      - "{{ orthanc_http_port }}:8042"
      - "{{ orthanc_dicom_port }}:4242"
    volumes:
      - "{{ orthanc_storage_dir }}/orthanc.json:/etc/orthanc/orthanc.json:ro"
    env:
      ORTHANC__NAME: "Orthanc Server"
