---
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - docker.io
    - ncdu
    - vim
    - rsyslog
    - htop
    - docker-compose
  # Edge case: pokud by nefungoval apt update (např. kvůli špatnému připojení), došlo by k selhání.

- name: Ensure Docker group exists
  group:
    name: docker
    state: present

- name: Create carebot user
  user:
    name: carebot
    groups: docker
    append: yes
    shell: /bin/bash
    create_home: yes
  # Edge case: uživatel může existovat

- name: Ensure rsyslog is running
  service:
    name: rsyslog
    state: started
    enabled: yes
  # Edge case: rsyslog nemusí být přítomný ve všech distribucích

- name: Ensure carebot can run Docker commands without sudo
  lineinfile:
    path: /etc/sudoers
    line: "carebot ALL=(ALL) NOPASSWD: /usr/bin/docker"
    validate: "visudo -cf %s"
  # Edge case: chybný zápis do sudoers může znepřístupnit sudo – validace se tomu snaží předcházet